@include('frontend-layouts.main')

<div class="rev-slider">
</div>
<div id="content" class="site-content"><div class="container"><div class="inner-wrapper">    

<div id="primary" class="content-area">
<main id="main" class="site-main" role="main">

			
				
<article id="post-52" class="post-52 page type-page status-publish hentry">
	<header class="entry-header">
		<h1 class="entry-title">Academics</h1>	</header><!-- .entry-header -->

	<div class="entry-content">
    		<p>LIS is one of the highly reputed school in City Nagda state MP. School offers English medium co-education studies. Course offered – NCERT syllabus approved by CBSE Delhi. LIS Management is in the process of getting CBSE- I affiliation so as to offer better education program to students of nearby locations.</p>
<p>We believe in modern science theory along with learning of enhancing values cultures. Study program at school is designed so as to offer a balanced life to students. Major emphasis is on providing quality education in the way to increase overall growth of a child and therefore we have designed a system of education wherein students get the opportunity to explore.</p>
<p>School is filled with exceptionally active environment where every student gets the opportunity to learn according to their capacity. LIS vision is to make children acquire knowledge and appreciation about their social and cultural heritage. LIS provides a vision to students about what they want to become in their respective life.</p>
<p>We provide best of education and facilities to the students to make them achieve new landmarks and success in various fields so that they carryout all the activities creatively. School is governed by highly qualified and active Principal along with the team of Teachers.</p>
<p>Complete development of a child’s mind is taken care of by us at School. LIS creates an opportunity for each and every student to experience artistic, intellectual and practical activities. </p>
<p>To provide a timely growth, school organizes Seminars and Workshops on frequent intervals for students and teachers. Our motto is to provide a better education facility to all the people who are residing in this small town Nagda city.</p>
<p>Having a sprawling campus with best of teaching and learning amenities, LIS believes in providing learning for the students that would prepare them to face all the challenges of 21st century.</p>
<p>&nbsp;</p>
					</div><!-- .entry-content -->

	<footer class="entry-footer">
			</footer><!-- .entry-footer -->
</article><!-- #post-## -->

				
			
		</main><!-- #main -->
	</div><!-- #primary -->



</div><!-- .inner-wrapper -->
</div><!-- .container -->
</div><!-- #content -->

@include('frontend-layouts.footer')


<!--Generated by Endurance Page Cache-->