@include('frontend-layouts.main')

<div class="rev-slider">
</div>
<div id="content" class="site-content"><div class="container"><div class="inner-wrapper">    

<div id="primary" class="content-area">
<main id="main" class="site-main" role="main">

			
				
<article id="post-1556" class="post-1556 page type-page status-publish hentry">
	<header class="entry-header">
		<h1 class="entry-title">Extra Curricular Activities</h1>	</header><!-- .entry-header -->

	<div class="entry-content">
    		<p>Lakshya International School offers extra curricular activities like music(vocal and instrumental), Dance, Art and Craft, Theater and Drama, Clubs are integral part of the education system in the school.</p>
<div class="row "><div class="col-lg-2 col-md-12 col-xs-12 col-sm-12">
<img src="http://lisnagda.org/wp-content/uploads/2017/03/music.jpg" class="img-responsive oscitas-res-image" alt="">
</div>
<div class="col-lg-10 col-md-12 col-xs-12 col-sm-12"></p>
<p><span style="color: #008000;"><strong>Music</strong></span></p>
<p>Music at our school is a soul enriching activity. Every pupil is encouraged to play at least one musical instrument /take singing lessons and appreciate music classes. Students are taken to concerts as a learning experience.</div>
</div>
<hr class=" rule-thin osc-rule" />
<div class="row "><div class="col-lg-2 col-md-12 col-xs-12 col-sm-12">
<img src="http://lisnagda.org/wp-content/uploads/2016/11/images76-150x150.jpeg" class="img-responsive oscitas-res-image" alt="">
</div>
<div class="col-lg-10 col-md-12 col-xs-12 col-sm-12"></p>
<p><span style="color: #008000;"><strong>Art</strong></span></p>
<p>A well‐equipped Art Room at our school develops confidence of the students and skills in areas such as drawing, painting, pottery, model making and sculpture. School organizes art workshops for the students and staff at regular intervals.</div>
</div>
<hr class=" rule-thin osc-rule" />
<div class="row "><div class="col-lg-2 col-md-12 col-xs-12 col-sm-12">
<img src="http://lisnagda.org/wp-content/uploads/2017/03/theater_drama-1.jpg" class="img-responsive oscitas-res-image" alt="">
</div>
<div class="col-lg-10 col-md-12 col-xs-12 col-sm-12"></p>
<p><span style="color: #008000;"><strong>Theater and Drama</strong></span></p>
<p>Students are exposed to all aspects of theater which includes lighting, production, stage design and costumes, through workshops conducted by experts at regular intervals.</div>
</div>
<hr class=" rule-thin osc-rule" />
<div class="row "><div class="col-lg-2 col-md-12 col-xs-12 col-sm-12">
<img src="http://lisnagda.org/wp-content/uploads/2017/03/club-1.jpg" class="img-responsive oscitas-res-image" alt="">
</div>
<div class="col-lg-10 col-md-12 col-xs-12 col-sm-12"></p>
<p><span style="color: #008000;"><strong>Play Zone</strong></span></p>
<p>Kids in the pre-primary section are often taken to play area wherein they are guided by the teachers about various games and activities. Students enjoy a lot in this kind of games and also at the same time their gross motor skills develop.</div>
</div>
<hr class=" rule-thin osc-rule" />
<div class="row "><div class="col-lg-2 col-md-12 col-xs-12 col-sm-12">
<img src="http://lisnagda.org/wp-content/uploads/2017/03/cricket1.jpg" class="img-responsive oscitas-res-image" alt="">
</div>
<div class="col-lg-10 col-md-12 col-xs-12 col-sm-12"></p>
<p><span style="color: #008000;"><strong>Outdoor Games</strong></span></p>
<p>Outdoor games like Cricket, Tennis, Football, Basketball and kho-kho was introduced initially and have been taken up their after for excellence, team spirit and physical fitness of the students.</div>
</div>
<hr class=" rule-thin osc-rule" />
<div class="row "><div class="col-lg-2 col-md-12 col-xs-12 col-sm-12">
<img src="http://lisnagda.org/wp-content/uploads/2017/03/swimming lis1.jpg" class="img-responsive oscitas-res-image" alt="">
</div>
<div class="col-lg-10 col-md-12 col-xs-12 col-sm-12"></p>
<p><span style="color: #008000;"><strong>Swimming</strong></span></p>
<p>A well designed swimming pool with precise specification often gives scope to students to learn and master the skills and techniques of swimming while helping in their physical development.</div>
</div>
<p>&nbsp;</p>
					</div><!-- .entry-content -->

	<footer class="entry-footer">
			</footer><!-- .entry-footer -->
</article><!-- #post-## -->

				
			
		</main><!-- #main -->
	</div><!-- #primary -->



</div><!-- .inner-wrapper -->
</div><!-- .container -->
</div><!-- #content -->
	
@include('frontend-layouts.footer')

<!--Generated by Endurance Page Cache-->